apiVersion : apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app : {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: {{ .Release.Name }}
  template:
    metadata:
      labels:
        project: {{ .Release.Name }}   # Service will look for those PODS Labels!!!
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: disktype
                operator: In
                values:
                - ssd
      containers:
        - name : {{ .Release.Name }}-web
          image: {{ .Values.container.image }}
          resources:
            requests:
              memory: {{ .Values.container.memory }}
              cpu: {{ .Values.container.cpu }}
          ports:
            - containerPort: 80
          env:
            - name: "token"
              valueFrom:
                secretKeyRef:
                  key:  token
                  name: app-secrets