{{- $secret := (lookup "v1" "Secret" .Release.Namespace "app-secrets") -}}

apiVersion: v1
kind: Secret
metadata:
  name: app-secrets

{{ if $secret -}}
data:
  token: {{ $secret.data.token }}
{{ else -}}
data:
  token: {{ .Values.token | b64enc }}
{{ end }}